import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} /> {/* Use the description from metadata */}
        <title>{metadata.title}</title> {/* Use the title from metadata */}
      </head>
      <body className={inter.className}>
        {children}
        <footer>
          <div>
            <h3>Policies:</h3>
            <ul>
              <li>
                <Link href="/PrivacyPolicy"> {/* Use the 'href' property of Link */}
                  Security and Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="/AcceptableUsePolicy"> {/* Use the 'href' property of Link */}
                  Acceptable Use Policy
                </Link>
              </li>
              <li>
                <Link href="/DMCAPolicy"> {/* Use the 'href' property of Link */}
                  DMCA Notice & Takedown Policy
                </Link>
              </li>
            </ul>
          </div>
        </footer>
      </body>
    </html>
  )
}

