import { Inter } from 'next/font/google';
import Link from 'next/link';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        <style>
          {`
            /* Add the styles for the links here */
            footer {
              text-align: center;
            }
            ul {
              list-style-type: none;
              padding: 0;
              display: flex;
              justify-content: center;
            }
            li {
              margin: 10px;
            }
            a {
              display: inline-block;
              padding: 10px 20px;
              border: 2px solid #0070f3;
              border-radius: 5px;
              text-decoration: none;
              color: white;
              transition: color 0.3s, background-color 0.3s;
            }
            a:hover {
              color: #0070f3;
              background-color: white;
            }
            /* Add styles for titles here */
            h3 {
              color: #0070f3; /* Bright blue color */
              font-weight: bold; /* Bolded text */
              font-size: 24px; /* Larger font size */
            }
          `}
        </style>
      </head>
      <body className={inter.className}>
        {children}
        <footer>
          <div>
            <h3>Policies:</h3> {/* Apply styles to these titles */}
            <ul>
              <li>
                <Link href="/PrivacyPolicy">
                  Security and Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="/AcceptableUsePolicy">
                  Acceptable Use Policy
                </Link>
              </li>
              <li>
                <Link href="/DMCAPolicy">
                  DMCA Notice & Takedown Policy
                </Link>
              </li>
            </ul>
          </div>
        </footer>
      </body>
    </html>
  );
}
